# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-30 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('modem', 'モデム'), ('wifi', 'ワイファイ'), ('none', 'なし')], max_length=15, verbose_name='利用状況')),
                ('career', models.CharField(choices=[('sb', 'Softbank'), ('au', 'au by KDDI'), ('dcm', 'Docomo'), ('rk', 'Rakuten mobile')], max_length=20)),
            ],
        ),
    ]
