# Generated by Django 2.1.5 on 2019-02-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themlp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='money',
            field=models.CharField(choices=[('cheaper', '2000円'), ('same', '3800円'), ('expensive', 'はい')], default='', max_length=20, verbose_name='現状利用価格'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='career',
            field=models.CharField(choices=[('sb', 'Softbank'), ('au', 'au by KDDI'), ('dcm', 'Docomo'), ('rk', 'Rakuten mobile')], max_length=20, verbose_name='キャリア'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('modem', 'モデム'), ('wifi', 'ポケットワイファイ'), ('none', 'なし')], max_length=15, verbose_name='利用状況'),
        ),
    ]
